<?php
// web_push.php — Pure PHP Web Push sender (no composer dependencies).
//
// Uses VAPID authentication and RFC 8291 payload encryption (AES-128-GCM + ECDH).
// Requires PHP 7.4+ with openssl extension.
//
// Usage:
//   require_once __DIR__ . '/web_push.php';
//   web_push_send($subscription, $payload);
//
// where $subscription = [
//   'endpoint' => 'https://fcm.googleapis.com/...',
//   'keys'     => ['p256dh' => '...', 'auth' => '...'],
// ];

if (!defined('WEB_PUSH_PRIVATE_KEY')) {
    define('WEB_PUSH_PRIVATE_KEY', '');
}
if (!defined('WEB_PUSH_SUBJECT')) {
    define('WEB_PUSH_SUBJECT', 'mailto:push@example.com');
}

// ── Base64 helpers ────────────────────────────────────────────

function web_push_urlsafe_b64_decode(string $input): string {
    $padding = str_repeat('=', (4 - strlen($input) % 4) % 4);
    return base64_decode(strtr($input, '-_', '+/') . $padding);
}

function web_push_urlsafe_b64_encode(string $input): string {
    return rtrim(strtr(base64_encode($input), '+/', '-_'), '=');
}

// ── VAPID key handling ───────────────────────────────────────

/**
 * Convert a raw URL-safe Base64 VAPID private key (32 bytes) to a PEM string
 * that openssl_sign() can use.
 *
 * VAPID keys generated by `npx web-push generate-vapid-keys` are raw
 * 32-byte private keys encoded as URL-safe Base64. PHP's openssl_sign()
 * expects a PEM-formatted EC private key (RFC 5915 DER → PEM).
 */
function web_push_raw_key_to_pem(string $rawBase64): string {
    // Decode URL-safe Base64 → raw bytes
    $raw = web_push_urlsafe_b64_decode($rawBase64);
    if (strlen($raw) !== 32) {
        throw new \RuntimeException('Invalid VAPID private key: expected 32 bytes, got ' . strlen($raw));
    }

    // Build DER-encoded ECPrivateKey (RFC 5915)
    // SEQUENCE { INTEGER(1), OCTET STRING(32 bytes), [0]{OID prime256v1} }
    $oid = "\x2A\x86\x48\xCE\x3D\x03\x01\x07"; // 1.2.840.10045.3.1.7 = prime256v1

    $seqContent = "\x02\x01\x01"              // version = 1
        . "\x04\x20" . $raw                  // OCTET STRING: 32-byte private key
        . "\xA0\x0A\x06\x08" . $oid;         // CONTEXT[0]: curve OID

    $der = "\x30" . chr(strlen($seqContent)) . $seqContent;

    return "-----BEGIN EC PRIVATE KEY-----\n"
        . chunk_split(base64_encode($der), 64)
        . "-----END EC PRIVATE KEY-----";
}

/**
 * Get PEM-formatted VAPID private key (caching the conversion).
 */
function web_push_get_private_key_pem(): string {
    static $pem = null;
    if ($pem !== null) return $pem;

    $raw = defined('WEB_PUSH_PRIVATE_KEY') ? WEB_PUSH_PRIVATE_KEY : getenv('WEB_PUSH_PRIVATE_KEY');
    if (empty($raw)) {
        throw new \RuntimeException('WEB_PUSH_PRIVATE_KEY not configured');
    }

    // If it's already PEM, use directly
    if (str_contains($raw, '-----BEGIN')) {
        $pem = $raw;
        return $pem;
    }

    // Convert raw Base64 to PEM
    $pem = web_push_raw_key_to_pem($raw);
    return $pem;
}

/**
 * Extract the uncompressed public key (65 bytes) from the VAPID key pair.
 */
function web_push_get_vapid_public_key_raw(): string {
    static $pub = null;
    if ($pub !== null) return $pub;

    $pem = web_push_get_private_key_pem();
    $key = openssl_pkey_get_private($pem);
    if (!$key) {
        throw new \RuntimeException('Failed to load VAPID private key: ' . openssl_error_string());
    }

    $details = openssl_pkey_get_details($key);
    if (!isset($details['ec']['x']) || !isset($details['ec']['y'])) {
        throw new \RuntimeException('VAPID key is not an EC key');
    }

    $pub = "\x04"
        . str_pad($details['ec']['x'], 32, "\x00", STR_PAD_LEFT)
        . str_pad($details['ec']['y'], 32, "\x00", STR_PAD_LEFT);

    return $pub;
}

// ── VAPID JWT ─────────────────────────────────────────────────

function web_push_vapid_jwt(string $audience): string {
    $privateKeyPem = web_push_get_private_key_pem();
    $subject = defined('WEB_PUSH_SUBJECT') ? WEB_PUSH_SUBJECT
        : (getenv('WEB_PUSH_SUBJECT') ?: 'mailto:push@example.com');

    $now = time();
    $header = ['typ' => 'JWT', 'alg' => 'ES256'];
    $claims = [
        'aud'  => $audience,
        'exp'  => $now + 12 * 3600, // 12 hours
        'sub'  => $subject,
    ];

    $headerB64  = web_push_urlsafe_b64_encode(json_encode($header, JSON_UNESCAPED_SLASHES));
    $claimsB64  = web_push_urlsafe_b64_encode(json_encode($claims, JSON_UNESCAPED_SLASHES));
    $input      = "{$headerB64}.{$claimsB64}";

    $ok = openssl_sign($input, $signature, $privateKeyPem, OPENSSL_ALGO_SHA256);
    if (!$ok) {
        throw new \RuntimeException('VAPID JWT signing failed: ' . openssl_error_string());
    }

    $signatureB64 = web_push_urlsafe_b64_encode($signature);
    return "{$input}.{$signatureB64}";
}

// ── RFC 8291 Payload Encryption (AES-128-GCM + ECDH) ────────

/**
 * Build a proper SubjectPublicKeyInfo PEM from a raw 65-byte uncompressed point.
 */
function web_push_build_public_key_pem(string $rawPoint): string {
    // Ensure the point has the 04 prefix
    if (strlen($rawPoint) === 64) {
        $rawPoint = "\x04" . $rawPoint;
    }

    // SubjectPublicKeyInfo DER for P-256:
    // SEQUENCE { SEQUENCE { OID(ecPublicKey), OID(prime256v1) }, BIT STRING(point) }
    $ecOid  = "\x06\x07\x2A\x86\x48\xCE\x3D\x02\x01"; // 1.2.840.10045.2.1
    $cvOid  = "\x06\x08\x2A\x86\x48\xCE\x3D\x03\x01\x07"; // prime256v1

    $algId = "\x30" . chr(strlen($ecOid) + strlen($cvOid)) . $ecOid . $cvOid;
    $bitStr = "\x03" . chr(strlen($rawPoint) + 1) . "\x00" . $rawPoint;
    $seqContent = $algId . $bitStr;

    $der = "\x30" . chr(strlen($seqContent)) . $seqContent;

    return "-----BEGIN PUBLIC KEY-----\n"
        . chunk_split(base64_encode($der), 64)
        . "-----END PUBLIC KEY-----";
}

function web_push_encrypt_payload(string $payload, string $userPublicKey, string $userAuth): array
{
    // Decode keys
    $userKeyRaw = web_push_urlsafe_b64_decode($userPublicKey);
    $authKey    = web_push_urlsafe_b64_decode($userAuth);

    // Generate local ECDH key pair
    $localKeyPair = openssl_pkey_new([
        'curve_name'     => 'prime256v1',
        'ec_private_key' => null,
    ]);
    if (!$localKeyPair) {
        throw new \RuntimeException('Failed to generate ECDH key pair: ' . openssl_error_string());
    }

    // Extract raw local public key (65 bytes: 04 || x || y)
    $localPubRaw = '';
    $details = openssl_pkey_get_details($localKeyPair);
    if (isset($details['ec']['x']) && isset($details['ec']['y'])) {
        $localPubRaw = "\x04"
            . str_pad($details['ec']['x'], 32, "\x00", STR_PAD_LEFT)
            . str_pad($details['ec']['y'], 32, "\x00", STR_PAD_LEFT);
    }
    if (strlen($localPubRaw) !== 65) {
        throw new \RuntimeException('Cannot extract local public key (got ' . strlen($localPubRaw) . ' bytes)');
    }

    // Build PEM for remote user's public key
    $userPubPem = web_push_build_public_key_pem($userKeyRaw);
    $userPubResource = openssl_pkey_get_public($userPubPem);
    if (!$userPubResource) {
        throw new \RuntimeException('Failed to parse user public key PEM: ' . openssl_error_string());
    }

    // ECDH shared secret
    // PHP 8.0+: openssl_pkey_derive (preferred)
    // PHP 7.x:   openssl_dh_compute_key (works with EC keys too)
    $shared = false;
    if (PHP_VERSION_ID >= 80000 && function_exists('openssl_pkey_derive')) {
        $shared = openssl_pkey_derive($userPubResource, $localKeyPair, 256);
    }
    if ($shared === false) {
        // Fallback for PHP 7.x: openssl_dh_compute_key(public_key, private_key)
        // Note: first param = REMOTE public key, second param = LOCAL private key
        $shared = openssl_dh_compute_key($userPubPem, $localKeyPair);
    }
    if ($shared === false) {
        throw new \RuntimeException(
            'ECDH shared secret computation failed: ' . openssl_error_string()
        );
    }

    // HKDF-Extract: PRK = HMAC-SHA256(salt=authKey, IKM=shared)
    $prk = hash_hmac('sha256', $shared, $authKey, true);

    // HKDF-Expand for multiple keys
    // HKDF-Expand(PRK, info || 0x00 || length, outputLen)
    $ikmInfo = function (string $label, int $len): string {
        // info = label + 0x00 + 0x00 (context = empty, length in bits)
        // Per RFC 8291: info = "Content-Encoding: <label>" + 0x00 + 0x00
        return web_push_hkdf_expand($prk, $label . "\x00\x00", $len);
    };

    // RFC 8291 key derivation
    $prkForKeys = hash_hmac('sha256', $shared . "\x00", $authKey . "\x00" . "\x00", true);
    // Simplified: just use the standard HKDF approach
    $clientToken = web_push_hkdf_expand($prk, "WebPush: info\x00", 16);
    $nonce       = web_push_hkdf_expand($prk, "Content-Encoding: nonce\x00\x00", 12);
    $cek         = web_push_hkdf_expand($prk, "Content-Encoding: aes128gcm\x00\x00", 16);

    // Encrypt payload with AES-128-GCM
    $tag = '';
    $ciphertext = openssl_encrypt($payload, 'aes-128-gcm', $cek, OPENSSL_RAW_DATA, $nonce, $tag);
    if ($ciphertext === false) {
        throw new \RuntimeException('AES-128-GCM encryption failed: ' . openssl_error_string());
    }

    // Build encrypted payload (RFC 8291 aes128gcm):
    // salt(16) || localPublicKey(65) || recordCount(1) || ciphertext || tag(16)
    $salt = random_bytes(16);
    $recordCount = "\x00\x00"; // 0 records before this (little-endian uint16)
    $result = $salt . $localPubRaw . $recordCount . $ciphertext . $tag;

    return [
        'body'    => web_push_urlsafe_b64_encode($result),
        'headers' => [
            'Content-Encoding' => 'aes128gcm',
            'Crypto-Key'       => 'p256ecdsa=' . web_push_urlsafe_b64_encode($localPubRaw),
        ],
    ];
}

function web_push_hkdf_expand(string $prk, string $info, int $length): string {
    $hashLen = 32; // SHA-256
    $n = (int) ceil($length / $hashLen);
    $okm = '';
    $t = '';

    for ($i = 1; $i <= $n; $i++) {
        $t = hash_hmac('sha256', $t . $info . chr($i), $prk, true);
        $okm .= $t;
    }

    return substr($okm, 0, $length);
}

// ── Main send function ────────────────────────────────────────

/**
 * Send a Web Push notification.
 *
 * @param array $subscription  ['endpoint' => ..., 'keys' => ['p256dh' => ..., 'auth' => ...]]
 * @param array $payload       Data to send (will be JSON-encoded)
 * @param int   $ttl           Time-to-live in seconds (default 4 hours)
 * @return bool  True on success
 */
function web_push_send(array $subscription, array $payload, int $ttl = 14400): bool
{
    $endpoint = $subscription['endpoint'] ?? '';
    $p256dh   = $subscription['keys']['p256dh'] ?? '';
    $auth     = $subscription['keys']['auth']   ?? '';

    if (empty($endpoint) || empty($p256dh) || empty($auth)) {
        error_log('WebPush: invalid subscription (missing endpoint/keys)');
        return false;
    }

    $jsonPayload = json_encode($payload, JSON_UNESCAPED_UNICODE);

    // 1. Encrypt payload
    try {
        $encrypted = web_push_encrypt_payload($jsonPayload, $p256dh, $auth);
    } catch (\Throwable $e) {
        error_log('WebPush encryption error: ' . $e->getMessage());
        return false;
    }

    // 2. Build VAPID JWT
    $origin = parse_url($endpoint, PHP_URL_ORIGIN);
    if (!$origin) {
        error_log('WebPush: cannot parse endpoint origin: ' . $endpoint);
        return false;
    }

    try {
        $jwt = web_push_vapid_jwt($origin);
    } catch (\Throwable $e) {
        error_log('WebPush VAPID JWT error: ' . $e->getMessage());
        return false;
    }

    // 3. Build Crypto-Key header (encryption key + VAPID public key)
    try {
        $vapidPub = web_push_get_vapid_public_key_raw();
    } catch (\Throwable $e) {
        $vapidPub = '';
        error_log('WebPush VAPID public key warning: ' . $e->getMessage());
    }

    $cryptoKey = $encrypted['headers']['Crypto-Key'];
    if (!empty($vapidPub)) {
        $cryptoKey .= '; p256ecdsa=' . web_push_urlsafe_b64_encode($vapidPub);
    }

    // 4. Send via cURL with Urgency: high for immediate mobile delivery
    $headers = [
        'Content-Type: application/octet-stream',
        'Authorization: vapid t=' . $jwt,
        'TTL: ' . $ttl,
        'Urgency: high',
        'Topic: ' . substr(hash('sha256', $endpoint), 0, 16),
        'Content-Encoding: ' . $encrypted['headers']['Content-Encoding'],
        'Crypto-Key: ' . $cryptoKey,
    ];

    $ch = curl_init($endpoint);
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_HTTPHEADER     => $headers,
        CURLOPT_POSTFIELDS     => $encrypted['body'],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 10,
        CURLOPT_CONNECTTIMEOUT => 5,
        CURLOPT_FOLLOWLOCATION => true,
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $curlError = curl_error($ch);
    curl_close($ch);

    if ($curlError) {
        error_log("WebPush cURL error: {$curlError}");
        return false;
    }

    if ($httpCode === 200 || $httpCode === 201) {
        return true;
    }

    error_log("WebPush push service error HTTP {$httpCode}: " . substr((string)$response, 0, 500));

    // 404 or 410 = subscription expired → should be cleaned up by caller
    return false;
}
